# Generated by Django 2.0.4 on 2018-04-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('symbol', models.CharField(max_length=10)),
                ('rank', models.IntegerField()),
                ('price_usd', models.DecimalField(decimal_places=10, max_digits=10)),
                ('price_btc', models.DecimalField(decimal_places=10, max_digits=10)),
                ('percent_change_1h', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
    ]
