# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_coin_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='percent_change_1h',
        ),
        migrations.AlterField(
            model_name='coin',
            name='price_btc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coin',
            name='price_usd',
            field=models.FloatField(),
        ),
    ]
