# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180418_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
