# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180418_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='id',
        ),
        migrations.AlterField(
            model_name='coin',
            name='symbol',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
