# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_coin_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='slug',
        ),
        migrations.AddField(
            model_name='coin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
